sed -i 's/M.\+//g' dos0.1,8.txt
sed -i 's/M.\+//g' dos0.1,10.txt
sed -i 's/M.\+//g' dos0.1,11.txt
sed -i 's/M.\+//g' dos1,2.txt
sed -i 's/M.\+//g' dos1,4.txt
sed -i 's/M.\+//g' dos1,6.txt
sed -i 's/M.\+//g' dos1,8.txt
sed -i 's/M.\+//g' dos1,10.txt
sed -i 's/M.\+//g' dos1,11.txt
sed -i 's/M.\+//g' dos10,2.txt
sed -i 's/M.\+//g' dos10,4.txt
sed -i 's/M.\+//g' dos10,6.txt
sed -i 's/M.\+//g' dos10,8.txt
sed -i 's/M.\+//g' dos10,11.txt
sed -i 's/M.\+//g' dos10,10.txt
